### PR TITLE
WDP220701-34 Add slider animation in Feedback

### PR DESCRIPTION
**Pull request by DmkMrw**

### CODE REVIEW

**Comment by evacu8** [comment]
Please change the animation duration and associated setTimeouts to 1s, as 2s seemed to sluggish and I shortened it in the page change task. 
Pull recent changes from master. Swipeable component is now animated so there is no need to animate sections inside it.

**Comment by milosz7** [comment]
I have been playing around with animations on other components and I feel like the best timing is 0.5s. To make the change even more smooth we can set timeout to page state change to half of the animation length so it updates when the opacity is 0. Let me know what you think

**Comment by DmkMrw** [comment]
I changed the times of the animation for 1s

**Comment by DmkMrw** [comment]
Let me know if everything is OK.

**Review by milosz7 — APPROVED** [review]
Looks good to me :)

**Comment by evacu8** [comment]
> I have been playing around with animations on other components and I feel like the best timing is 0.5s. To make the change even more smooth we can set timeout to page state change to half of the animation length so it updates when the opacity is 0. Let me know what you think

Looks like the animation that I made on Swipeable component does not switch the page exactly in the middle. I will fix it.

**Pull request merged**
